### ISSUE TITLE
Request for help: Code for sampling with pre-trained Stable Diffusion model

### ISSUE THREAD

**Issue by EnableAsync** [uzn36/AttributeSwitching#1]
I have read your paper with great interest and am now examining the associated GitHub repository. In the paper, you mention using a pre-trained Stable Diffusion model for sampling. However, I cannot locate the relevant code for this process in the public repository.
Could you please provide some guidance on where to find the code related to sampling with the pre-trained Stable Diffusion model? If it's not currently in the repository, would it be possible to add it or provide some instructions on how to implement this part?

**Comment by uzn36** [comment]
sorry for forgetting to upload the code. I uploaded that code at [pretrained_diffuser_switching.ipynb](https://github.com/uzn36/AttributeSwitching/blob/main/pretrained_diffuser_switching.ipynb).

**Comment by EnableAsync** [comment]
Thank you very much for your helpful response. I greatly appreciate your time and assistance.

I'll now close this issue.
